# Generated by Django 3.0.6 on 2020-05-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(choices=[('one', 'GRADE ONE'), ('two', 'GRADE TWO'), ('three', 'GRADE Three'), ('four', 'GRADE Four'), ('five', 'GRADE Five'), ('six', 'GRADE Six')], max_length=10),
        ),
    ]
