# Generated by Django 3.0.6 on 2020-08-03 09:52

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200715_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='id_no',
            field=models.IntegerField(validators=[main.validators.validate_id_no]),
        ),
    ]
