# Generated by Django 3.0.6 on 2020-08-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200803_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'others')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='religion',
            field=models.CharField(choices=[('atheists', 'atheists'), ("baha'i", "Baha'i"), ('buddhism', 'buddhism'), ('christianity', 'christianity'), ('hinduism', 'hinduism'), ('islam', 'islam'), ('jainism', 'jainism'), ('judaism', 'judaism'), ('shintoism', 'shintoism'), ('sikhism', 'sikhism'), ('syncretic', 'syncretic'), ('taoism', 'taoism'), ('tradition', 'tradition'), ('zoroastrianism', 'zoroastrianism')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, to='main.Subject'),
        ),
    ]
