# Generated by Django 3.0.6 on 2020-05-31 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPupil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school_type', models.CharField(choices=[('pu', 'Public'), ('pr', 'Private')], default='pu', max_length=3)),
                ('county', models.CharField(max_length=50)),
                ('constitutuency', models.CharField(max_length=50)),
                ('ward', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_status', models.CharField(choices=[('p', 'Permanent'), ('t', 'Temporary')], max_length=2)),
                ('position', models.CharField(choices=[('ht', 'HeadTeacher'), ('dt', 'Deputy Teacher'), ('s', 'staff')], default='s', max_length=3)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institution.School')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('teacher', models.ManyToManyField(to='institution.SchoolTeacher')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institution.School')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institution.School')),
            ],
        ),
        migrations.CreateModel(
            name='PupilRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pupil', models.ManyToManyField(to='institution.ClassPupil')),
            ],
        ),
        migrations.CreateModel(
            name='GradeSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institution.SchoolGrade')),
                ('school_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institution.SchoolSubject')),
                ('subject_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.SchoolTeacher')),
            ],
        ),
        migrations.CreateModel(
            name='GradeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50)),
                ('class_teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.SchoolTeacher')),
                ('school_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institution.SchoolGrade')),
            ],
        ),
        migrations.AddField(
            model_name='classpupil',
            name='grade_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.GradeClass'),
        ),
        migrations.AddField(
            model_name='classpupil',
            name='pupil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.Pupil'),
        ),
    ]
